version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/frontend
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/frontend-deploy.sh
      timeout: 300
      runas: ubuntu